// Generated by CoffeeScript 1.8.0
(function() {
  var URI, argv, i, mmmst, queryWord, request, searchNumber, url, _i;

  mmmst = require('minimist');

  argv = mmmst(process.argv.slice(2));

  if (!argv.q || !argv.n) {
    console.log("please -q and -n options");
    return;
  }

  queryWord = argv.q;

  if (isNaN(argv.n) === true) {
    console.log("please -q input number");
  }

  searchNumber = argv.n;

  if (100 < searchNumber) {
    console.log("oh big number");
  }

  searchNumber = Math.ceil(searchNumber);

  URI = require('URIjs');

  for (i = _i = 1; 1 <= searchNumber ? _i <= searchNumber : _i >= searchNumber; i = 1 <= searchNumber ? ++_i : --_i) {
    url = new URI('http://ajax.googleapis.com/ajax/services/search/images');
    url.addSearch({
      q: queryWord,
      v: "1.0",
      hl: "ja",
      safe: "off",
      start: i
    });
    request = require("request");
    request(url.toString(), function(err, res, body) {
      var data, result, _j, _len, _ref, _results;
      if (!err || res.statusCode === 200) {
        data = JSON.parse(body);
        _ref = data.responseData.results;
        _results = [];
        for (_j = 0, _len = _ref.length; _j < _len; _j++) {
          result = _ref[_j];
          _results.push(console.log(result.unescapedUrl));
        }
        return _results;
      } else {
        console.log("error: " + res.statusCode);
      }
    });
  }

}).call(this);
